"""
build_commensurate_moire.py

Construction of commensurate twisted MX2 (transition-metal dichalcogenide)
bilayers, with explicit commensurability enforcement and end-to-end geometric
validation.

Version: 3.0

Changes relative to v2.0
------------------------
1. FIXED (silent, structural): the supercell vectors and the sense of the
   top-layer rotation were mutually inconsistent.  A vector v belongs to the
   coincidence-site lattice (CSL) iff  v in L  AND  R(-theta) v in L.  For
   (m, n) = (17, 16) and a +theta rotation, v = m*c1 + n*c2 fails the second
   condition, so the rotated layer was NOT periodic under the supercell it was
   wrapped into.  Atom count and nearest-neighbour checks both pass anyway, so
   the defect was invisible to v2.0's validation.  The CSL is generated by
       T1 = n*c1 + m*c2,   T2 = -m*c1 + (m + n)*c2.

2. FIXED (silent, structural): each layer is now enumerated from its OWN
   primitive vectors.  Building the top layer by rotating the bottom layer's
   in-cell sites is wrong: the CSL is invariant under R(-theta) but not under
   R(+theta), so the rotated representatives are not a valid set of coset
   representatives.  Wrapping them collapsed 102 pairs of atoms onto identical
   positions for the (17, 16) cell.

3. FIXED (physics-relevant): the rotation origin was the geometric cell centre,
   0.5*(T1 + T2), which is not a lattice site.  Rotating about a non-lattice
   point displaces the rotated lattice by (I - R) c, an arbitrary translation,
   leaving the AA stacking point undefined.  Both layers now share the origin as
   a lattice site, so AA sits at the cell corner by construction, and registry
   is changed only through an explicit rigid shift of the top layer.

4. Exact twist angle via atan2 rather than arccos (arccos loses roughly half the
   mantissa as theta -> 0, which matters for the sub-1-degree cells needed to
   reach 20 nm moire periods).

5. Validation replaced.  Commensurability is asserted algebraically; every atom
   is mapped back to its ideal lattice site; neighbour distances use the
   minimum-image convention.  v2.0 compared raw Cartesian positions, so a seam
   defect at the periodic boundary -- exactly what a non-commensurate cell
   produces -- was invisible.  Atom counting alone cannot detect any of the
   three bugs above.

6. Heterobilayer input (a_top != a_bot) is accepted but flagged: exact
   pure-twist commensuration requires a single lattice constant, so the top
   layer is strained to match and both the applied strain and the true
   unstrained heterostructure moire period are reported.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Sequence

import numpy as np
from ase import Atoms

__all__ = [
    "MoireMetadata",
    "MoireStructure",
    "build_commensurate_moire",
    "commensurate_angle",
    "coincidence_vectors",
    "assert_commensurate",
    "find_commensurate_pair",
    "print_report",
    "write_xyz",
    "write_lammps",
]


# =============================================================================
# METADATA
# =============================================================================


@dataclass(slots=True)
class MoireMetadata:
    """Everything needed to reproduce and audit the structure."""

    m: int
    n: int

    theta_rad: float
    theta_deg: float

    a_bottom: float
    a_top_nominal: float
    top_layer_strain: float

    primitive_vectors: np.ndarray
    supercell_vectors: np.ndarray

    moire_period: float
    true_hetero_period: Optional[float]

    n_cells: int
    n_atoms: int

    registry_shift_frac: np.ndarray
    interlayer_d: float

    max_deviation_from_ideal: float
    min_interatomic_distance: float
    min_MX_bond: float

    warnings: list = field(default_factory=list)


@dataclass(slots=True)
class MoireStructure:
    atoms: Atoms
    metadata: MoireMetadata


# =============================================================================
# GEOMETRY
# =============================================================================


def primitive_vectors(a: float) -> tuple[np.ndarray, np.ndarray]:
    """Hexagonal primitive vectors, c1 along +x, 60 degrees apart."""
    c1 = np.array([a, 0.0])
    c2 = np.array([a / 2.0, a * np.sqrt(3.0) / 2.0])
    return c1, c2


def commensurate_angle(m: int, n: int) -> float:
    """
    Exact twist angle for the (m, n) commensurate rotation.

    Defined by the angle between  m*c1 + n*c2  and  n*c1 + m*c2:

        cos(theta) = (m^2 + n^2 + 4mn) / (2 (m^2 + mn + n^2))
        sin(theta) = sqrt(3) (m^2 - n^2) / (2 (m^2 + mn + n^2))

    atan2 of the two numerators retains full double precision; arccos of the
    cosine alone loses roughly half the significant digits as theta -> 0.
    """
    y = np.sqrt(3.0) * (m * m - n * n)
    x = m * m + n * n + 4 * m * n
    return float(np.arctan2(y, x))


def rotation_matrix(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s], [s, c]])


def coincidence_vectors(
    c1: np.ndarray, c2: np.ndarray, m: int, n: int
) -> tuple[np.ndarray, np.ndarray]:
    """
    Generators of the coincidence-site lattice for the (m, n) rotation, assuming
    the top layer is rotated by +theta about the origin.

        T1 = n*c1 + m*c2
        T2 = -m*c1 + (m + n)*c2

    Note the index order: T1 uses (n, m), not (m, n).  Both generators satisfy
    R(-theta) T in L, i.e. they are simultaneously lattice vectors of the
    unrotated and the rotated layer.  The cell is rhombic, |T1| = |T2|, with a
    60 degree included angle.
    """
    T1 = n * c1 + m * c2
    T2 = -m * c1 + (m + n) * c2
    return T1, T2


def n_cells(m: int, n: int) -> int:
    return m * m + m * n + n * n


# =============================================================================
# COMMENSURABILITY
# =============================================================================


def assert_commensurate(
    c1: np.ndarray,
    c2: np.ndarray,
    T1: np.ndarray,
    T2: np.ndarray,
    theta: float,
    tol: float = 1e-8,
) -> None:
    """
    Assert that T1 and T2 are coincidence-site-lattice vectors:

        T in L   and   R(-theta) T in L.

    Algebraic, costs microseconds, and fails loudly for the v2.0
    supercell/rotation-sense mismatch that no atom-count or nearest-neighbour
    check can detect.
    """
    A = np.column_stack((c1, c2))
    Rm = rotation_matrix(-theta)

    for name, T in (("T1", T1), ("T2", T2)):
        for label, v in ((name, T), (f"R(-theta) {name}", Rm @ T)):
            frac = np.linalg.solve(A, v)
            if not np.allclose(frac, np.round(frac), atol=tol):
                raise RuntimeError(
                    f"Non-commensurate supercell: {label} has fractional "
                    f"coordinates {frac} in the primitive basis, which are not "
                    f"integers.  The rotated layer would not be periodic under "
                    f"this cell."
                )


# =============================================================================
# BASIS
# =============================================================================


def basis_atoms(symbol_M: str, symbol_X: str, h_X: float):
    """
    2H-MX2 monolayer basis: in-plane fractional coordinates plus a Cartesian z.

    Both chalcogens sit at the SAME in-plane site (1/3, 1/3), displaced only
    along z.  This is eclipsed trigonal-prismatic coordination with six equal
    M-X bonds.  Placing them at (1/3, 2/3) and (2/3, 1/3) instead gives an
    unphysical antiprismatic environment with unequal bonds.
    """
    return [
        (symbol_M, np.array([0.0, 0.0]), 0.0),
        (symbol_X, np.array([1.0 / 3.0, 1.0 / 3.0]), +h_X),
        (symbol_X, np.array([1.0 / 3.0, 1.0 / 3.0]), -h_X),
    ]


# =============================================================================
# PER-LAYER SITE ENUMERATION
# =============================================================================


def enumerate_layer_sites(
    d1: np.ndarray,
    d2: np.ndarray,
    T1: np.ndarray,
    T2: np.ndarray,
    expected: int,
    eps: float = 1e-9,
) -> np.ndarray:
    """
    Enumerate the sites of the lattice spanned by (d1, d2) that lie inside the
    supercell (T1, T2), i.e. with fractional coordinates in [0, 1) x [0, 1).

    Each layer must be enumerated from its own primitive vectors.  Rotating the
    other layer's in-cell sites does not work: the CSL is invariant under
    R(-theta) but not under R(+theta), so rotated representatives are not a
    valid set of coset representatives and collapse onto each other on wrapping.

    The half-open interval uses a small negative tolerance so a site at
    fractional -1e-16 is kept while one at 1 - 1e-16 is dropped, giving exactly
    `expected` representatives with no duplicates.
    """
    S = np.column_stack((T1, T2))
    Sinv = np.linalg.inv(S)

    scale = max(np.linalg.norm(T1), np.linalg.norm(T2)) / min(
        np.linalg.norm(d1), np.linalg.norm(d2)
    )
    reach = int(np.ceil(2.0 * scale)) + 2

    idx = np.arange(-reach, reach + 1)
    I, J = np.meshgrid(idx, idx, indexing="ij")
    sites = I.ravel()[:, None] * d1 + J.ravel()[:, None] * d2

    frac = sites @ Sinv.T
    keep = np.all((frac >= -eps) & (frac < 1.0 - eps), axis=1)
    out = sites[keep]

    if len(out) != expected:
        raise RuntimeError(
            f"Enumeration produced {len(out)} lattice sites but the supercell "
            f"contains exactly {expected}.  Search reach or tolerance is wrong."
        )
    return out


def build_layer(
    sites: np.ndarray,
    d1: np.ndarray,
    d2: np.ndarray,
    basis,
    z_shift: float,
    in_plane_shift: np.ndarray,
):
    """Place the MX2 basis on every lattice site of one layer."""
    symbols, positions = [], []

    for symbol, frac_xy, dz in basis:
        offset = frac_xy[0] * d1 + frac_xy[1] * d2
        xy = sites + offset + in_plane_shift
        z = np.full(len(xy), dz + z_shift)
        positions.append(np.column_stack((xy, z)))
        symbols.extend([symbol] * len(xy))

    return symbols, np.vstack(positions)


# =============================================================================
# VALIDATION
# =============================================================================


def deviation_from_ideal(
    positions: np.ndarray,
    d1: np.ndarray,
    d2: np.ndarray,
    basis,
    in_plane_shift: np.ndarray,
    z_shift: float,
) -> float:
    """
    Map every atom of one layer back onto its ideal lattice site and return the
    largest deviation, in Angstrom.

    Wrapping the cell adds a supercell vector T; because T is a coincidence
    vector it is a lattice vector of both layers, so integrality survives
    wrapping.  A non-zero deviation therefore means the cell is not a true
    coincidence cell.
    """
    A = np.column_stack((d1, d2))
    xy = positions[:, :2] - in_plane_shift
    z_rel = positions[:, 2] - z_shift

    worst = 0.0
    for _, frac_xy, dz in basis:
        sel = np.isclose(z_rel, dz, atol=1e-6)
        if not np.any(sel):
            continue
        offset = frac_xy[0] * d1 + frac_xy[1] * d2
        frac = np.linalg.solve(A, (xy[sel] - offset).T).T
        residual = frac - np.round(frac)
        dev = np.linalg.norm(residual @ A.T, axis=1)
        worst = max(worst, float(dev.max()))

    return worst


def neighbour_diagnostics(atoms: Atoms) -> tuple[float, float]:
    """
    Return (smallest interatomic distance, smallest M-X bond) under the
    minimum-image convention.

    v2.0 compared raw Cartesian positions, which cannot see a pair that is close
    only across a periodic boundary -- precisely where a non-commensurate cell
    produces its seam defect.
    """
    from ase.neighborlist import neighbor_list

    metals = {"Mo", "W"}
    sym = np.array(atoms.get_chemical_symbols())

    d_min = float("inf")
    mx_min = float("inf")

    for cutoff in (1.0, 2.0, 3.2, 4.0):
        i, j, d = neighbor_list("ijd", atoms, cutoff)
        if not len(d):
            continue
        d_min = min(d_min, float(d.min()))
        is_mx = np.array(
            [(sym[a] in metals) != (sym[b] in metals) for a, b in zip(i, j)]
        )
        if is_mx.any():
            mx_min = min(mx_min, float(d[is_mx].min()))
        if np.isfinite(d_min) and np.isfinite(mx_min):
            break

    return d_min, mx_min


# =============================================================================
# COMMENSURATE PAIR SEARCH
# =============================================================================


def find_commensurate_pair(
    target_theta_deg: float,
    max_index: int = 80,
    max_atoms: Optional[int] = None,
    top: int = 10,
) -> list[dict]:
    """
    Enumerate (m, n) pairs and return those closest to a target twist angle.

    Each entry carries the exact angle, cell count, atom count and moire period
    in units of the lattice constant, so angular accuracy can be traded against
    system size explicitly rather than by guesswork.
    """
    out = []
    for m in range(1, max_index + 1):
        for n in range(0, m):
            N = n_cells(m, n)
            natoms = 6 * N
            if max_atoms is not None and natoms > max_atoms:
                continue
            theta = np.degrees(commensurate_angle(m, n))
            out.append(
                {
                    "m": m,
                    "n": n,
                    "theta_deg": theta,
                    "n_cells": N,
                    "n_atoms": natoms,
                    "period_over_a": float(np.sqrt(N)),
                    "delta_deg": abs(theta - target_theta_deg),
                }
            )
    out.sort(key=lambda r: (r["delta_deg"], r["n_atoms"]))
    return out[:top]


# =============================================================================
# MAIN BUILDER
# =============================================================================


def build_commensurate_moire(
    symbol_M_bottom: str = "Mo",
    symbol_X_bottom: str = "Se",
    symbol_M_top: Optional[str] = None,
    symbol_X_top: Optional[str] = None,
    a: float = 3.288,
    a_top: Optional[float] = None,
    h_X: float = 1.664,
    interlayer_d: float = 6.50,
    m: int = 17,
    n: int = 16,
    vacuum: float = 18.0,
    registry_shift_frac: Sequence[float] = (0.0, 0.0),
) -> MoireStructure:
    """
    Build a commensurate twisted MX2 bilayer.

    Parameters
    ----------
    a, a_top
        Lattice constants of the bottom and top layers.  If `a_top` differs from
        `a`, the top layer is strained to `a`, because exact pure-twist
        commensuration requires a single lattice constant.  The applied strain
        and the true unstrained heterostructure moire period are recorded in the
        metadata and raised as a warning.
    registry_shift_frac
        Rigid in-plane shift of the top layer, in fractional coordinates of the
        primitive cell.  (0, 0) is AA (metal over metal at the cell corner);
        (1/3, 1/3) and (2/3, 2/3) are the two inequivalent AB/BA stackings.  A
        rigid shift commutes with the lattice translations, so it changes the
        local registry without breaking commensurability.  This is the knob that
        corresponds to a GSFE stacking-energy scan.
    """
    warnings: list[str] = []

    if not (m > n >= 0):
        raise ValueError(f"Require m > n >= 0; got m={m}, n={n}.")

    symbol_M_top = symbol_M_top or symbol_M_bottom
    symbol_X_top = symbol_X_top or symbol_X_bottom

    a_top_nominal = a if a_top is None else a_top
    strain = (a - a_top_nominal) / a_top_nominal

    theta = commensurate_angle(m, n)
    N = n_cells(m, n)

    c1, c2 = primitive_vectors(a)
    T1, T2 = coincidence_vectors(c1, c2, m, n)
    assert_commensurate(c1, c2, T1, T2, theta)

    R = rotation_matrix(theta)
    d1, d2 = R @ c1, R @ c2

    if abs(strain) > 1e-12:
        delta = abs(a - a_top_nominal) / a
        true_period = a / float(np.hypot(delta, theta))
        warnings.append(
            f"Heterobilayer input: top layer strained by {strain * 100:+.3f}% to "
            f"enforce commensuration.  The unstrained moire period would be "
            f"{true_period / 10:.3f} nm, versus "
            f"{a * np.sqrt(N) / 10:.3f} nm for the strained cell built here."
        )
    else:
        true_period = None

    sites_bot = enumerate_layer_sites(c1, c2, T1, T2, N)
    sites_top = enumerate_layer_sites(d1, d2, T1, T2, N)

    shift_frac = np.asarray(registry_shift_frac, dtype=float)
    in_plane_shift = shift_frac[0] * d1 + shift_frac[1] * d2

    basis_bot = basis_atoms(symbol_M_bottom, symbol_X_bottom, h_X)
    basis_top = basis_atoms(symbol_M_top, symbol_X_top, h_X)

    sym_b, pos_b = build_layer(sites_bot, c1, c2, basis_bot, 0.0, np.zeros(2))
    sym_t, pos_t = build_layer(sites_top, d1, d2, basis_top, interlayer_d, in_plane_shift)

    max_dev = max(
        deviation_from_ideal(pos_b, c1, c2, basis_bot, np.zeros(2), 0.0),
        deviation_from_ideal(pos_t, d1, d2, basis_top, in_plane_shift, interlayer_d),
    )

    positions = np.vstack((pos_b, pos_t))
    symbols = sym_b + sym_t

    z_lo, z_hi = positions[:, 2].min(), positions[:, 2].max()
    cell_z = (z_hi - z_lo) + vacuum
    positions[:, 2] += 0.5 * cell_z - 0.5 * (z_hi + z_lo)

    cell = np.array([[T1[0], T1[1], 0.0], [T2[0], T2[1], 0.0], [0.0, 0.0, cell_z]])
    atoms = Atoms(symbols=symbols, positions=positions, cell=cell, pbc=[True, True, False])
    atoms.wrap()

    expected_atoms = 6 * N
    if len(atoms) != expected_atoms:
        raise RuntimeError(f"Expected {expected_atoms} atoms, built {len(atoms)}.")

    if max_dev > 1e-6:
        raise RuntimeError(
            f"Atoms deviate from their ideal lattice sites by up to "
            f"{max_dev:.3e} A; the cell is not a true coincidence cell."
        )

    d_min, mx_min = neighbour_diagnostics(atoms)
    if d_min < 1.5:
        raise RuntimeError(f"Atomic overlap under minimum image: {d_min:.4f} A.")

    if vacuum < 12.0:
        warnings.append(f"Vacuum {vacuum:.1f} A may be too thin for a DFT slab.")

    meta = MoireMetadata(
        m=m,
        n=n,
        theta_rad=theta,
        theta_deg=float(np.degrees(theta)),
        a_bottom=a,
        a_top_nominal=a_top_nominal,
        top_layer_strain=strain,
        primitive_vectors=np.array([c1, c2]),
        supercell_vectors=np.array([T1, T2]),
        moire_period=float(np.linalg.norm(T1)),
        true_hetero_period=true_period,
        n_cells=N,
        n_atoms=len(atoms),
        registry_shift_frac=shift_frac,
        interlayer_d=interlayer_d,
        max_deviation_from_ideal=max_dev,
        min_interatomic_distance=d_min,
        min_MX_bond=mx_min,
        warnings=warnings,
    )
    return MoireStructure(atoms=atoms, metadata=meta)


# =============================================================================
# IO / REPORT
# =============================================================================


def write_xyz(structure: MoireStructure, filename: str) -> None:
    structure.atoms.write(filename, format="extxyz")


def write_lammps(structure: MoireStructure, filename: str) -> None:
    from ase.io import write

    write(filename, structure.atoms, format="lammps-data")


def print_report(structure: MoireStructure) -> None:
    md = structure.metadata
    print("=" * 74)
    print(" COMMENSURATE MOIRE STRUCTURE REPORT")
    print("=" * 74)
    print(f"  (m, n)                  : ({md.m}, {md.n})")
    print(f"  twist angle             : {md.theta_deg:.8f} deg")
    print(f"  primitive cells         : {md.n_cells}")
    print(f"  atoms                   : {md.n_atoms}")
    print(f"  moire period            : {md.moire_period:.4f} A "
          f"= {md.moire_period / 10:.4f} nm")
    if md.true_hetero_period is not None:
        print(f"  unstrained hetero period: {md.true_hetero_period / 10:.4f} nm")
    print(f"  lattice constant        : {md.a_bottom:.4f} A  "
          f"(top nominal {md.a_top_nominal:.4f}, strain {md.top_layer_strain * 100:+.3f}%)")
    print(f"  interlayer distance     : {md.interlayer_d:.3f} A")
    print(f"  registry shift (frac)   : ({md.registry_shift_frac[0]:.4f}, "
          f"{md.registry_shift_frac[1]:.4f})   [AA at cell corner]")
    print("  supercell vectors (A)   :")
    for v in md.supercell_vectors:
        print(f"      [{v[0]:13.6f} {v[1]:13.6f} ]")
    print("-" * 74)
    print(f"  max deviation from ideal lattice : {md.max_deviation_from_ideal:.3e} A")
    print(f"  min interatomic distance (MIC)   : {md.min_interatomic_distance:.4f} A")
    print(f"  min M-X bond (MIC)               : {md.min_MX_bond:.4f} A")
    for w in md.warnings:
        print(f"  [warning] {w}")
    print("=" * 74)


if __name__ == "__main__":
    print_report(build_commensurate_moire(m=17, n=16))
